= Release notes

== version 1.5

- _dynamic_ environment

- `grid3.mas2j`

== version 1.4

- separation of problem _detection_ (based on strategy ONE in selectOption) and _recovery_ (based on internal action that produces a new plan)

- `grid2.mas2j`

== version 1.3

- _multi-agent_ case: one agent is Jason(F) others are regular agents
- matrix runs several agents (models) in a shared environment (model)
- bridge scenario. the best solution is to use ONE strategy with recovery plan (see bridge2.mas2j and bridge_fut_recovery.asl). see also results1.3.adoc for more details

== version 1.2

- consolidate results
- minor changes

== version 1.1

- more grid scenarios: U, H, O and improved GUI
- initial experiments
- consider cost
- uses priority queue (cost+preference)
- new strategy: solve_m
- notion of zone1: all "first level" options = first options (from default options) + options until failure using policy
- cost weight: a number that distinguishes the 3 strategies (no more specific algorithms, just this parameter)

== version 1.0

- scenario line ok

- store solution found when looking ahead and use it (do not reconsider options every step)

- type of problem: handles goal not achieved
- considers preference

- strategies: one, solve_(p|f), using a (no priority) queue

- generic for any Jason program (given and environment model)
